apiVersion: ENC[AES256_GCM,data:yS0=,iv:dn5MZ/8I2yOhOQrkrbsKrJht8U00qOBdxiVGDFtQj84=,tag:xCSJnVJ73RcRtVL5ImT6Fw==,type:str]
kind: ENC[AES256_GCM,data:oE87pWaW,iv:e2Aa/AZaHSW3nb9yb653j4ORAzRLoeJHFMRJdssy4xw=,tag:cF+4GJAmITvjKAAqTBImCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:joYQwzdafapHukY=,iv:nXbg+qejpvw7oYDNhqIEvkfMyKq4bC1ox2BHY8I2EFs=,tag:suUaiCQGXHoVt/7djTmhYw==,type:str]
    namespace: ENC[AES256_GCM,data:T3FOHBYDCg==,iv:hYqkLp2AkAq1vjNmZRKL0brKi1tU9f9HlObTXl3fbnw=,tag:+6tbSUU21I5ZznmGvT+qZA==,type:str]
type: ENC[AES256_GCM,data:wEj/ntx3,iv:lRp0HQSE3hTECuSXKDlR6/cwJZzg9iwaQjVg5fzS8b4=,tag:WuArPDmSvJl/Qygmr96Vdw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:kHFQ90rwIHW1Gp9yhOgI4c5UrF/S9gRbqlCMIUM=,iv:30BwhAeVXuDTl9ccGAuIwwPVeNwtJ4GcXX0tE5r5jgU=,tag:8ct2Jd/jQwmzM5BXZjkIkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUUlJanA2SFF0Yi9pVXpu
            YmNpc2pmYmlvN3JOWFhZWWtVUVR4ZzM3eWowCmh0S2tvRXE0eDJDVGxkRkxrQ2lJ
            NjhMcjM3UUQ0dCswNkg5MFZTWElJekUKLS0tIHlTSmFyVnpKRG54R3A1RTNYMzRP
            ZjNwaUg4eXNJTXh2N1c0VG11RTNyaDAK5chL6sKV8pN+IWxAFQxT9N9c+PtTzd6D
            5Zy5gz3hE+UwYRaZzJPBVRqFh61wwT29OIJ8npPpGsITC4ehyb1eRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xkml9mahqjh8cvpcqpaw3r3y8wsg3kxx58tsa2thjm47hptlgflsnkmpll
    lastmodified: "2026-09-16T15:32:29Z"
    mac: ENC[AES256_GCM,data:XpvtpQjYjCcbYl24bS8w1epI9IRhRwrMIoNSPKW76K4gj793VhrR4VSAOISU6ws2dlxmEntINBRQOnI6/zGimcloglNz5IT7W3JBV/joYSvMObJyNc5Bt7OArbF7HAJcPXiwRV0wG/8u+sbF/zjyb3n18wj9GCSRw1AjusPGktA=,iv:mi4mtWbwC+0sUBaGGKT8wxcLgrztD6WCWIQPazS1lTc=,tag:U8hB7fZgkLvoA/zPMzXj/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
